#!/usr/bin/env bash
# trouble shooting why our server is not working
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
